name: Deploy Frontend to AWS

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build React App

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: ./frontend

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          coche-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Build React App
        run: npm run build
        working-directory: ./frontend

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build/
          retention-days: 1

  deploy:
    name: Deploy React App to S3 and CloudFront
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: build/

      - name: Configure AWS Credentials
        uses: actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: us-east-2

      - name: Sync Build Files to S3
        run: |
          aws s3 sync ./build s3://${{ secrets.FRONTEND_BUCKET }} --delete

      - name: Create CloudFront Invalidation
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ vars.FRONTEND_CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"


